# Generated by Django 5.2.17 on 2026-08-21 16:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmpresaBanquetera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=150)),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                (
                    "rfc",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="RFC / identificación fiscal",
                    ),
                ),
                ("telefono_contacto", models.CharField(blank=True, max_length=20)),
                ("email_contacto", models.EmailField(blank=True, max_length=254)),
                (
                    "direccion_bodega_central",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Dirección de la bodega/comisariato central",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Empresa Banquetera",
                "verbose_name_plural": "Empresas Banqueteras",
                "ordering": ["nombre_comercial"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PLANNER", "Event Planner"),
                            ("DIRECTO", "Cliente Directo"),
                        ],
                        default="DIRECTO",
                        max_length=10,
                    ),
                ),
                (
                    "nombre_agencia_planner",
                    models.CharField(blank=True, max_length=150),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
                (
                    "numero_invitados",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "estado_semaforo",
                    models.CharField(
                        choices=[
                            ("PROSPECTO", "🟡 Prospecto"),
                            ("APARTADO", "🟠 Contratado sin anticipo"),
                            ("CONFIRMADO", "🔴 Confirmado"),
                        ],
                        default="PROSPECTO",
                        max_length=12,
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("PLANNER", "Con Event Planner"),
                            ("DIRECTO", "Cliente Directo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha_cotizacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_vencimiento_prospecto",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("fecha_limite_anticipo", models.DateField(blank=True, null=True)),
                (
                    "fecha_registro_anticipo",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "autorizado_proveedor_externo",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿Administrador autorizó renta de equipo externo?",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="core.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "unidad_base",
                    models.CharField(
                        choices=[
                            ("G", "Gramos"),
                            ("KG", "Kilogramos"),
                            ("ML", "Mililitros"),
                            ("L", "Litros"),
                            ("PZA", "Pieza"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "porcentaje_merma",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Ej. 0.12 representa 12% de merma",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo",
                "verbose_name_plural": "Insumos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="InventarioEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej. Plato hondo entrada, Copa de vino, Tenedor trinche",
                        max_length=150,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VAJILLA", "Vajilla / Loza"),
                            ("CRISTALERIA", "Cristalería"),
                            ("CUBERTERIA", "Cubertería"),
                            ("MOBILIARIO", "Mobiliario"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("stock_disponible", models.PositiveIntegerField(default=0)),
                (
                    "costo_reposicion_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario_equipo",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo de Inventario",
                "verbose_name_plural": "Inventario de Equipo",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RecetaMaestra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tiempo_menu",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("FUERTE", "Plato fuerte"),
                            ("POSTRE", "Postre"),
                            ("BEBIDA", "Bebida"),
                            ("BOTANA", "Botana / Coctel"),
                        ],
                        default="FUERTE",
                        max_length=20,
                        verbose_name="Tiempo del menú",
                    ),
                ),
                (
                    "porciones_base",
                    models.PositiveIntegerField(
                        help_text="Número de porciones sobre el que está capturada la receta (ej. 1 o 10).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo estimado de la receta completa para `porciones_base` porciones.",
                        max_digits=10,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta Maestra",
                "verbose_name_plural": "Recetario Maestro",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PruebaMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prueba", models.DateField()),
                (
                    "asistentes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "notas_chef",
                    models.TextField(
                        blank=True,
                        verbose_name="Historial de modificaciones culinarias del Chef",
                    ),
                ),
                ("aprobado", models.BooleanField(default=False)),
                (
                    "cobro_adicional_generado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruebas_menu",
                        to="core.evento",
                    ),
                ),
                (
                    "platos_a_probar",
                    models.ManyToManyField(
                        blank=True, related_name="pruebas", to="core.recetamaestra"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba de Menú",
                "verbose_name_plural": "Pruebas de Menú",
                "ordering": ["fecha_prueba"],
            },
        ),
        migrations.CreateModel(
            name="IngredienteReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cantidad de este insumo necesaria para `porciones_base` porciones de la receta.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("G", "Gramos"),
                            ("KG", "Kilogramos"),
                            ("ML", "Mililitros"),
                            ("L", "Litros"),
                            ("PZA", "Pieza"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_en_recetas",
                        to="core.insumo",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="core.recetamaestra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente de Receta",
                "verbose_name_plural": "Ingredientes de Receta",
            },
        ),
        migrations.CreateModel(
            name="DetalleMenuEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notas_personalizacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Notas de personalización para este evento",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_menu",
                        to="core.evento",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_en_eventos",
                        to="core.recetamaestra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Menú de Evento",
                "verbose_name_plural": "Detalles de Menú de Evento",
            },
        ),
        migrations.CreateModel(
            name="RegistroRoturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_rota",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "costo_reposicion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo total de reposición para esta rotura (cantidad x costo unitario).",
                        max_digits=10,
                    ),
                ),
                (
                    "registrado_por",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Capitán de Meseros que registró el conteo",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("pdf_cargo_danos_generado", models.BooleanField(default=False)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roturas",
                        to="core.inventarioequipo",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_rotura",
                        to="core.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Rotura",
                "verbose_name_plural": "Registros de Roturas",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="SedeEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del jardín/salón"
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                (
                    "notas_acceso_carga",
                    models.TextField(
                        blank=True, verbose_name="Notas de acceso para carga y descarga"
                    ),
                ),
                ("disponibilidad_agua", models.BooleanField(default=True)),
                ("disponibilidad_luz", models.BooleanField(default=True)),
                (
                    "capacidad_maxima_invitados",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("restricciones_operativas", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedes",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede de Evento",
                "verbose_name_plural": "Sedes de Evento",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="core.sedeevento",
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                fields=("empresa", "telefono"),
                name="unique_cliente_telefono_por_empresa",
            ),
        ),
        migrations.AddConstraint(
            model_name="insumo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="unique_insumo_nombre_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventarioequipo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="unique_articulo_nombre_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="recetamaestra",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="unique_receta_nombre_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientereceta",
            constraint=models.UniqueConstraint(
                fields=("receta", "insumo"), name="unique_insumo_por_receta"
            ),
        ),
        migrations.AddConstraint(
            model_name="detallemenuevento",
            constraint=models.UniqueConstraint(
                fields=("evento", "receta"), name="unique_receta_por_evento"
            ),
        ),
        migrations.AddConstraint(
            model_name="sedeevento",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="unique_sede_nombre_por_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(
                fields=["empresa", "fecha", "estado_semaforo"],
                name="core_evento_empresa_a6997b_idx",
            ),
        ),
    ]
