# Generated by Django 5.2.17 on 2026-08-21 17:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaCargaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "conteo_retorno_completado",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿El Capitán de Meseros ya hizo el conteo de retorno?",
                    ),
                ),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_carga",
                        to="core.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Carga de Evento",
                "verbose_name_plural": "Listas de Carga de Evento",
            },
        ),
        migrations.CreateModel(
            name="DetalleListaCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.PositiveIntegerField(
                        help_text="Piezas necesarias para atender a los invitados, sin margen de seguridad."
                    ),
                ),
                (
                    "surtido",
                    models.BooleanField(
                        default=False, verbose_name="¿Ya se cargó al camión?"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_lista_carga",
                        to="core.inventarioequipo",
                    ),
                ),
                (
                    "lista_carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.listacargaevento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Lista de Carga",
                "verbose_name_plural": "Detalles de Lista de Carga",
                "ordering": ["articulo__tipo", "articulo__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lista_carga", "articulo"),
                        name="unique_articulo_por_lista_carga",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequerimientoEquipoTiempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tiempo_menu",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("FUERTE", "Plato fuerte"),
                            ("POSTRE", "Postre"),
                            ("BEBIDA", "Bebida"),
                            ("BOTANA", "Botana / Coctel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_por_invitado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Ej. 1 pieza por invitado. Puede ser fraccionario (ej. 0.5 si se comparte).",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requerimientos_por_tiempo",
                        to="core.inventarioequipo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requerimientos_equipo",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requerimiento de Equipo por Tiempo de Menú",
                "verbose_name_plural": "Requerimientos de Equipo por Tiempo de Menú",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "tiempo_menu", "articulo"),
                        name="unique_requerimiento_equipo_por_tiempo",
                    )
                ],
            },
        ),
    ]
