# Generated by Django 5.2.17 on 2026-08-25 09:49

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listacargaevento_detallelistacarga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCotizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costo_base_por_persona",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo variable de alimentos/servicio por invitado.",
                        max_digits=8,
                    ),
                ),
                (
                    "costos_fijos_transporte_personal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costos fijos del evento (transporte, personal base) a repartir entre los invitados.",
                        max_digits=10,
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_cotizador",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Cotizador",
                "verbose_name_plural": "Configuración del Cotizador",
            },
        ),
        migrations.CreateModel(
            name="EsquemaPagoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esquema_pago",
                        to="core.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Esquema de Pago de Evento",
                "verbose_name_plural": "Esquemas de Pago de Evento",
            },
        ),
        migrations.CreateModel(
            name="PersonalEventual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "rol_principal",
                    models.CharField(
                        choices=[
                            ("MESERO", "Mesero"),
                            ("BARTENDER", "Bartender"),
                            ("GARROTERO", "Garrotero"),
                            ("CAPITAN", "Capitán de Meseros"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        verbose_name="¿Disponible para postularse a vacantes?",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_eventual",
                        to="core.empresabanquetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Eventual",
                "verbose_name_plural": "Personal Eventual",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("POSTULADO", "Postulado"),
                            ("ACEPTADO", "Aceptado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="POSTULADO",
                        max_length=12,
                    ),
                ),
                ("postulado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to="core.personaleventual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postulación",
                "verbose_name_plural": "Postulaciones",
                "ordering": ["-postulado_en"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_verificacion",
                    models.CharField(
                        default=core.models._generar_codigo_checkin,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("hora_checkin", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmado_por",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Nombre de quien confirmó (ej. Capitán de Meseros)",
                    ),
                ),
                (
                    "postulacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in",
                        to="core.postulacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-In de Personal",
                "verbose_name_plural": "Check-Ins de Personal",
            },
        ),
        migrations.CreateModel(
            name="VacanteEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("MESERO", "Mesero"),
                            ("BARTENDER", "Bartender"),
                            ("GARROTERO", "Garrotero"),
                            ("CAPITAN", "Capitán de Meseros"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "tarifa_por_turno",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacantes",
                        to="core.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacante de Evento",
                "verbose_name_plural": "Vacantes de Evento",
                "ordering": ["evento__fecha"],
            },
        ),
        migrations.AddField(
            model_name="postulacion",
            name="vacante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postulaciones",
                to="core.vacanteevento",
            ),
        ),
        migrations.CreateModel(
            name="AbonoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "ANTICIPO",
                                "Anticipo (50%) — apartado y firma de contrato",
                            ),
                            (
                                "INTERMEDIO",
                                "Pago intermedio (30%) — fecha de prueba de menú",
                            ),
                            (
                                "LIQUIDACION",
                                "Liquidación (20%) — 15 días antes del evento",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_limite", models.DateField()),
                ("pagado", models.BooleanField(default=False)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "esquema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="core.esquemapagoevento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de Evento",
                "verbose_name_plural": "Abonos de Evento",
                "ordering": ["fecha_limite"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("esquema", "tipo"), name="unique_tipo_abono_por_esquema"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vacanteevento",
            constraint=models.UniqueConstraint(
                fields=("evento", "rol"), name="unique_rol_por_vacante_evento"
            ),
        ),
        migrations.AddConstraint(
            model_name="postulacion",
            constraint=models.UniqueConstraint(
                fields=("vacante", "personal"), name="unique_postulacion_por_vacante"
            ),
        ),
    ]
