# Generated by Django 5.2.17 on 2026-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_configuracioncotizador_esquemapagoevento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroroturas",
            name="costo_reposicion",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Costo total de reposición para esta rotura (cantidad x costo unitario). Se calcula solo.",
                max_digits=10,
            ),
        ),
    ]
