# Generated by Django 5.2.17 on 2026-08-25 10:30, hand-edited: un campo
# unique=True con default aleatorio no se puede agregar en un solo paso
# cuando ya hay filas existentes (todas recibirían el MISMO valor al
# evaluarse el callable una sola vez), así que se hace en 3 pasos:
# 1) se agrega el campo sin la restricción unique, 2) se le da un valor
# distinto a cada evento ya existente, 3) recién ahí se activa unique=True.

import core.models
from django.db import migrations, models


def generar_tokens_unicos(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    for evento in Evento.objects.all():
        evento.token_planner = core.models._generar_token_planner()
        evento.save(update_fields=["token_planner"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_registroroturas_costo_reposicion"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="token_planner",
            field=models.CharField(max_length=64, null=True, editable=False),
        ),
        migrations.RunPython(generar_tokens_unicos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evento",
            name="token_planner",
            field=models.CharField(
                default=core.models._generar_token_planner,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
