# Generated by Django 5.2.17 on 2026-08-25 10:59
#
# Además del cambio de etiqueta del campo, esta migración hace el backfill
# de las reglas automáticas del Módulo A para eventos que ya existían antes
# de que existiera esta lógica: les da un plazo fresco a partir de hoy en
# vez de dejarlos sin fecha de vencimiento (lo que nunca los vencería) o
# marcarlos vencidos de golpe justo al desplegar (lo que sería una sorpresa
# desagradable el mismo día del deploy).

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_fechas_vencimiento(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")

    def _sumar_dias_habiles(fecha_inicio, dias_habiles):
        fecha = fecha_inicio
        agregados = 0
        while agregados < dias_habiles:
            fecha += timedelta(days=1)
            if fecha.weekday() < 5:
                agregados += 1
        return fecha

    Evento.objects.filter(
        estado_semaforo="PROSPECTO", fecha_vencimiento_prospecto__isnull=True
    ).update(fecha_vencimiento_prospecto=timezone.now() + timedelta(hours=72))

    for evento in Evento.objects.filter(
        estado_semaforo="APARTADO",
        fecha_limite_anticipo__isnull=True,
        fecha_registro_anticipo__isnull=True,
    ):
        evento.fecha_limite_anticipo = _sumar_dias_habiles(timezone.localdate(), 5)
        evento.save(update_fields=["fecha_limite_anticipo"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_evento_token_planner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="autorizado_proveedor_externo",
            field=models.BooleanField(
                default=False,
                help_text="Actívalo si ya resolviste por fuera (renta externa, personal extra) que este día esté saturado de loza o personal en el sistema. Con esto el bloqueo automático de capacidad del Módulo A deja pasar este evento aunque el inventario interno no alcance.",
                verbose_name="¿Administrador ya autorizó cubrir por fuera el faltante de equipo o personal de este día? (renta externa / staff extra)",
            ),
        ),
        migrations.RunPython(backfill_fechas_vencimiento, migrations.RunPython.noop),
    ]
