# Generated by Django 5.2.17 on 2026-08-25 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_evento_autorizado_proveedor_externo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresabanquetera",
            name="dias_habiles_limite_anticipo",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Ej. 5 = un Apartado se marca 'Vencido' y libera la fecha si no llega el anticipo en 5 días hábiles.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Días hábiles para recibir el anticipo de un Apartado",
            ),
        ),
        migrations.AddField(
            model_name="empresabanquetera",
            name="horas_vencimiento_prospecto",
            field=models.PositiveIntegerField(
                default=72,
                help_text="Ej. 72 = un Prospecto se marca 'Vencido' solo si en 72 horas no pasa a Apartado o Confirmado.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Horas para que venza un Prospecto sin avanzar",
            ),
        ),
    ]
