# Generated by Django 5.2.17 on 2026-08-25 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_empresabanquetera_dias_habiles_limite_anticipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonoevento",
            name="alerta_enviada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="abonoevento",
            name="fecha_alerta_enviada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresabanquetera",
            name="dias_anticipacion_alerta_abono",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Ej. 3 = se manda el correo de recordatorio cuando falten 3 días o menos para la fecha límite de un abono (sin haber vencido todavía).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Días de anticipación para avisar por correo que un abono está por vencer",
            ),
        ),
    ]
