# Generated by Django 5.2.17 on 2026-08-25 23:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_abonoevento_alerta_enviada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresabanquetera",
            name="costo_extra_por_asistente_prueba_menu",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ej. 150.00 = si el límite de cortesía es 4 y se agenda una prueba con 6 asistentes, se genera automáticamente un cobro adicional de $300.00 (2 asistentes de más x $150.00). Déjalo en 0 para no generar cobro automático.",
                max_digits=10,
                verbose_name="Costo por cada asistente que exceda el límite de cortesía en una prueba de menú",
            ),
        ),
    ]
